apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: thumbnail
data:
  SQS_QUEUE_URL: https://sqs.ap-southeast-2.amazonaws.com/359707702022/thumbnail-pipeline-queue
  AWS_REGION: ap-southeast-2
  S3_BUCKET: thumbnail-pipeline-pala3105
  WORKER_NAMESPACE: thumbnail
