name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

# Shared env vars injected into every job
env:
  TF_VAR_s3_bucket_name:   ${{ secrets.S3_BUCKET_NAME }}

jobs:

  # ════════════════════════════════════════════════════════════
  # APPLY ALL
  # ════════════════════════════════════════════════════════════

  network-primary:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region:     ap-southeast-2
      - uses: hashicorp/setup-terraform@v3
      - name: Apply-Plan
        run: |
          cd terraform
            terraform init -reconfigure
            if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve
            else
            terraform plan
            fi
